Dom document loading
js-tasks-ru/js-20230223_dmitriy-ladutko pull request #5
Opened 2023-03-10 22:24 UTC by DmitriyLadutsko

2023-03-10 22:25 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-11 00:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-11 13:14 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static targetElement = document.body;
почему данное поле статическое?
и почему в это поле записана ссылка на `document.body`?

2023-03-11 13:14 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (NotificationMessage.targetElement && NotificationMessage.targetElement.querySelector('.notification')) {
🔴 please don't do this
так делать нельзя! 
подумайте что нужно записать в статическое св-во!
это явно не `document.body`

2023-03-11 13:15 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +const directions = {
почему данный объект и ф-ция "болтаются" за пределами класса?

2023-03-11 13:16 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  (row1, row2) => directions[order] * (row1[field] - row2[field]);
а что будет если `sortType` равен "foo-bar"?

2023-03-11 13:19 UTC, dosandk requested changes
решение `NotificationMessage` следует поправить, посмотрите пожалуйста коменты

2023-03-11 18:51 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-11 18:52 UTC, DmitriyLadutsko commented on 05-dom-document-loading/1-notification/index.js
> +  static targetElement = document.body;
Исправил. Описал в комментарии ниже
Спасибо!

2023-03-11 18:58 UTC, DmitriyLadutsko commented on 05-dom-document-loading/1-notification/index.js
> +    if (NotificationMessage.targetElement && NotificationMessage.targetElement.querySelector('.notification')) {
положил в статические свойства две переменные: 
1. **Ссылка на _инстанс_ предыдущей нотификации.** В случае наличия - выполняем на ней destroy раньше положенного срока, также обнуляем, как только таймаут закончился
2.  **ID таймера,** чтобы сделать его очистку (_clearTimeout_) при наличие еще жизнеспособного инстанса предыдущей нотификации

2023-03-11 18:58 UTC, DmitriyLadutsko commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +const directions = {
думал об утилитном использовании.. 
поправил

2023-03-11 18:59 UTC, DmitriyLadutsko commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  (row1, row2) => directions[order] * (row1[field] - row2[field]);
понял: нет дефолтного поведения. исправил в новой версии

2023-03-11 19:00 UTC, DmitriyLadutsko commented
@dosandk , спасибо! 
всё исправил

2023-03-11 19:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-11 19:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-11 20:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-13 13:49 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (NotificationMessage.targetElement && NotificationMessage.targetElement.querySelector('.notification')) {
👍 good

2023-03-13 13:49 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (NotificationMessage.previous) {
👍 good

2023-03-13 13:49 UTC, dosandk approved these changes
👍 good

2023-03-13 13:50 UTC, merged